--- 
title: "Prediction of Heart Attack"
author: "Yiming Zhu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Proposal
Developing a Machine Learning Model to Predict the Risk of Heart Attack Using Heart Attack Analysis & Prediction Dataset

Introduction:
Cardiovascular diseases (CVDs) are the leading cause of mortality worldwide, accounting for 17.9 million deaths annually or 31% of all deaths globally. Early diagnosis and care of people with CVDs or those at high cardiovascular risk can significantly improve outcomes. Heart attacks and strokes, which account for four out of every five CVD fatalities, can occur before the age of 70, highlighting the importance of early detection. Therefore, this project aims to develop a machine learning model to predict the risk of heart attack using the Heart Attack Analysis & Prediction Dataset.

Objectives:
The primary goal of this project is to predict the probability of a person having a heart attack based on their gender, age, and cholesterol level using a linear model as the baseline model, a logistic model, and a random forest model. Additionally, the results of all three models will be compared with the "HeartDisease" variable, which is the prediction of possibility of heart attack provided by the data author.

Methods:
The Heart Attack Analysis & Prediction Dataset will be used for this project, which includes 11 variables, including age, sex, exercise-induced angina, number of major vessels, chest pain type, resting blood pressure, cholestoral, fasting blood sugar, resting electrocardiographic results, ST depression induced by exercise relative to rest, and the target variable for heart attack prediction.

Three models will be developed and compared to predict the risk of heart attack, including a linear model as the baseline model, a logistic model, and a random forest model. The models will be evaluated using accuracy, sensitivity, and specificity metrics, and the best-performing model will be selected for further analysis.


The developed machine learning model will provide an accurate prediction of the probability of a person having a heart attack based on their gender, age, and cholesterol level. The results will be compared with the prediction of heart attack provided by the data author to determine the model's effectiveness in detecting heart attack risk. The project's findings will contribute to the early detection and prevention of heart attacks, ultimately improving patient outcomes.


This repo was initially generated from a bookdown template available here: https://github.com/jtr13/IMLVtemplate.




Data source: https://archive.ics.uci.edu/ml/datasets/Heart+Disease (UCI)
