# [Model 1]
Firstly, we load the data and convert all chracter variables to factor variables. 
```{r}
library(caret)
heart = read.csv('heart.csv')
heart$Sex=as.factor(heart$Sex)
heart$ChestPainType=as.factor(heart$ChestPainType)
heart$ExerciseAngina=as.factor(heart$ExerciseAngina)
heart$ST_Slope=as.factor(heart$ST_Slope)
heart$RestingECG=as.factor(heart$RestingECG)
str(heart)
```
Firstly, we split data with 80/20. 

```{r}
set.seed(5293)
train_split <- createDataPartition(heart$HeartDisease, p = 0.80, list = FALSE)
train_data <- heart[train_split,]
test_data <- heart[-train_split,]
```

Then we predict the logistic regression on all the variables. 

```{r}
lm.model <- lm(HeartDisease ~ ., data = train_data)
summary(lm.model)

lm.prediction <- predict(lm.model, newdata = test_data, type = "response")
lm.prediction <- ifelse(lm.prediction >= 0.5, 1, 0)

table(test_data$HeartDisease, lm.prediction)
sum(test_data$HeartDisease==lm.prediction) / nrow(test_data)
```
The accuracy rate is 89.61749%. 
